# Generated by Django 4.0.5 on 2022-07-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
