# Generated by Django 4.0.5 on 2022-07-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_video_delete_productvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecificationvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_spec', to='store.product'),
        ),
    ]
