# Generated by Django 4.0.5 on 2022-06-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_seller_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
