# Generated by Django 4.0.5 on 2022-06-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_seller_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='seller_profile_images'),
        ),
    ]
